### PR TITLE
TAB-006-Guideline-For-Contribution

### PR DESCRIPTION
**Pull request by takasurazeem**
TAB-006-Guideline-For-Contribution
A guideline for contributing to the repo.

related to: TAB-006(https://tabacus.atlassian.net/browse/TAB-6)
Signed-off-by: Takasur Azeem <takasurazeem@gmail.com>

### CODE REVIEW

**Comment by Tallak-Lippe** [comment]
Looking good

**Review by Tallak-Lippe — APPROVED** [review]
Looks good, well written and easy to follow

**Comment by Tallak-Lippe** [comment]
Should we rebase?

**Comment by Jakayus** [comment]
Great README!

**Review by Jakayus — APPROVED** [review]
Good overview of process and directions.

**Comment by Jakayus** [comment]
No conflicts and reviews are complete. Merging.

**Pull request merged**
